{{/*
SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "retail-shopping-assistant.serviceAccountName" . }}
  namespace: {{ include "retail-shopping-assistant.namespace" . }}
  labels:
    {{- include "retail-shopping-assistant.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
# RoleBinding to allow the service account to pull images from the internal OpenShift registry
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "retail-shopping-assistant.serviceAccountName" . }}-image-puller
  namespace: {{ include "retail-shopping-assistant.namespace" . }}
  labels:
    {{- include "retail-shopping-assistant.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
  - kind: ServiceAccount
    name: {{ include "retail-shopping-assistant.serviceAccountName" . }}
    namespace: {{ include "retail-shopping-assistant.namespace" . }}
{{- end }}
